spring.datasource.url=jdbc:mysql://localhost:3306/smarthire_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=smarthire-super-secret-key-2024-must-be-at-least-32-characters-long
jwt.expiration=86400000